spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: highway_to_hell
  expire: 36000
server:
  port: 8088